In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME", "SPECIAL_CONSIDERATIONS", "STATUS"],1)
application_df.head()

<ipython-input-2-2cbb3953e8a5>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  application_df = application_df.drop(["EIN", "NAME", "SPECIAL_CONSIDERATIONS", "STATUS"],1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,6692,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,142590,1

In [3]:
# Determine the number of unique values in each column.
app_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df.APPLICATION_TYPE.value_counts()
app_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Visualize the value counts of APPLICATION_TYPE
app_type_counts.plot.density()

In [6]:
# Determine which values to replace if counts are less than ...?
replace_application = list(app_type_counts[app_type_counts < 500].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
app_class_counts = application_df.CLASSIFICATION.value_counts()
app_class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# Visualize the value counts of CLASSIFICATION
app_class_counts.plot.density()

In [9]:
# Determine which values to replace if counts are less than ..?
replace_class = list(app_class_counts[app_class_counts < 1500].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Generate our categorical variable lists
app_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE    9
AFFILIATION         6
CLASSIFICATION      6
USE_CASE            5
ORGANIZATION        4
INCOME_AMT          9
dtype: int64

In [11]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[app_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(app_cat)
encode_df.head()

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(app_cat,1)
application_df.head()

<ipython-input-12-f28eb7bbd381>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  application_df = application_df.drop(app_cat,1)

,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=28)

<ipython-input-13-99378d8154c2>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = application_df.drop(["IS_SUCCESSFUL"],1).values

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  12
hidden_nodes_layer2 = 6

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 12)                492
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 78
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7
=================================================================
Total params: 577
Trainable params: 577
Non-trainable params: 0
_________________________________________________________________

In [16]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints_optimized_v3/",exist_ok=True)
checkpoint_path = "checkpoints_optimized_v3/weights.{epoch:02d}.hdf5"

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=4000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

Epoch 1/100
804/804 [==============================] - 1s 631us/step - loss: 0.6089 - accuracy: 0.6875
Epoch 2/100
804/804 [==============================] - 1s 639us/step - loss: 0.5647 - accuracy: 0.7241
Epoch 3/100
804/804 [==============================] - 1s 642us/step - loss: 0.5598 - accuracy: 0.7282
Epoch 4/100
804/804 [==============================] - 1s 649us/step - loss: 0.5569 - accuracy: 0.7275
Epoch 5/100
714/804 [=========================>....] - ETA: 0s - loss: 0.5561 - accuracy: 0.7284
Epoch 00005: saving model to checkpoints_optimized_v3\weights.05.hdf5
804/804 [==============================] - 1s 648us/step - loss: 0.5556 - accuracy: 0.7285
Epoch 6/100
804/804 [==============================] - 1s 623us/step - loss: 0.5540 - accuracy: 0.7287
Epoch 7/100
804/804 [==============================] - 1s 633us/step - loss: 0.5535 - accuracy: 0.7287
Epoch 8/100
804/804 [==============================] - 1s 639us/step - loss: 0.5531 - accuracy: 0.7294
Epoch 9/100
804/804 [==============================] - 0s 618us/step - loss: 0.5524 - accuracy: 0.7291
Epoch 10/100
709/804 [=========================>....] - ETA: 0s - loss: 0.5523 - accuracy: 0.7273
Epoch 00010: saving model to checkpoints_optimized_v3\weights.10.hdf5
804/804 [==============================] - 1s 654us/step - loss: 0.5519 - accuracy: 0.7290
Epoch 11/100
804/804 [==============================] - 1s 642us/step - loss: 0.5516 - accuracy: 0.7286
Epoch 12/100
804/804 [==============================] - 1s 624us/step - loss: 0.5512 - accuracy: 0.7296
Epoch 13/100
804/804 [==============================] - 0s 613us/step - loss: 0.5509 - accuracy: 0.7280
Epoch 14/100
804/804 [==============================] - 0s 618us/step - loss: 0.5504 - accuracy: 0.7290
Epoch 15/100
722/804 [=========================>....] - ETA: 0s - loss: 0.5492 - accuracy: 0.7299
Epoch 00015: saving model to checkpoints_optimized_v3\weights.15.hdf5
804/804 [==============================] - 1s 637us/step - loss: 0.5503 - accuracy: 0.7294
Epoch 16/100
804/804 [==============================] - 0s 616us/step - loss: 0.5498 - accuracy: 0.7301
Epoch 17/100
804/804 [==============================] - 0s 619us/step - loss: 0.5493 - accuracy: 0.7297
Epoch 18/100
804/804 [==============================] - 0s 612us/step - loss: 0.5490 - accuracy: 0.7312
Epoch 19/100
804/804 [==============================] - 0s 616us/step - loss: 0.5488 - accuracy: 0.7314
Epoch 20/100
712/804 [=========================>....] - ETA: 0s - loss: 0.5491 - accuracy: 0.7300
Epoch 00020: saving model to checkpoints_optimized_v3\weights.20.hdf5
804/804 [==============================] - 1s 648us/step - loss: 0.5485 - accuracy: 0.7300
Epoch 21/100
804/804 [==============================] - 1s 644us/step - loss: 0.5482 - accuracy: 0.7311
Epoch 22/100
804/804 [==============================] - 1s 626us/step - loss: 0.5479 - accuracy: 0.7309
Epoch 23/100
804/804 [==============================] - 1s 659us/step - loss: 0.5482 - accuracy: 0.7297
Epoch 24/100
804/804 [==============================] - 0s 617us/step - loss: 0.5479 - accuracy: 0.7305
Epoch 25/100
647/804 [=======================>......] - ETA: 0s - loss: 0.5482 - accuracy: 0.7324
Epoch 00025: saving model to checkpoints_optimized_v3\weights.25.hdf5
804/804 [==============================] - 1s 639us/step - loss: 0.5480 - accuracy: 0.7308
Epoch 26/100
804/804 [==============================] - 1s 642us/step - loss: 0.5475 - accuracy: 0.7309
Epoch 27/100
804/804 [==============================] - 1s 672us/step - loss: 0.5471 - accuracy: 0.7315
Epoch 28/100
804/804 [==============================] - 1s 681us/step - loss: 0.5474 - accuracy: 0.7317
Epoch 29/100
804/804 [==============================] - 1s 669us/step - loss: 0.5474 - accuracy: 0.7313
Epoch 30/100
668/804 [=======================>......] - ETA: 0s - loss: 0.5481 - accuracy: 0.7311
Epoch 00030: saving model to checkpoints_optimized_v3\weights.30.hdf5
804/804 [==============================] - 1s 680us/step - loss: 0.5471 - accuracy: 0.7319
Epoch 31/100
804/804 [==============================] - 0s 612us/step - loss: 0.5469 - accuracy: 0.7310
Epoch 32/100
804/804 [==============================] - 0s 618us/step - loss: 0.5465 - accuracy: 0.7311
Epoch 33/100
804/804 [==============================] - 0s 613us/step - loss: 0.5469 - accuracy: 0.7315
Epoch 34/100
804/804 [==============================] - 0s 613us/step - loss: 0.5466 - accuracy: 0.7309
Epoch 35/100
628/804 [======================>.......] - ETA: 0s - loss: 0.5461 - accuracy: 0.7311
Epoch 00035: saving model to checkpoints_optimized_v3\weights.35.hdf5
804/804 [==============================] - 1s 654us/step - loss: 0.5464 - accuracy: 0.7306
Epoch 36/100
804/804 [==============================] - 1s 624us/step - loss: 0.5469 - accuracy: 0.7314
Epoch 37/100
804/804 [==============================] - 0s 617us/step - loss: 0.5461 - accuracy: 0.7325
Epoch 38/100
804/804 [==============================] - 0s 612us/step - loss: 0.5462 - accuracy: 0.7324
Epoch 39/100
804/804 [==============================] - 1s 627us/step - loss: 0.5462 - accuracy: 0.7313
Epoch 40/100
571/804 [====================>.........] - ETA: 0s - loss: 0.5444 - accuracy: 0.7328
Epoch 00040: saving model to checkpoints_optimized_v3\weights.40.hdf5
804/804 [==============================] - 1s 629us/step - loss: 0.5461 - accuracy: 0.7319
Epoch 41/100
804/804 [==============================] - 0s 612us/step - loss: 0.5460 - accuracy: 0.7309
Epoch 42/100
804/804 [==============================] - 1s 639us/step - loss: 0.5460 - accuracy: 0.7322
Epoch 43/100
804/804 [==============================] - 0s 613us/step - loss: 0.5459 - accuracy: 0.7319
Epoch 44/100
804/804 [==============================] - 0s 616us/step - loss: 0.5459 - accuracy: 0.7315
Epoch 45/100
566/804 [====================>.........] - ETA: 0s - loss: 0.5449 - accuracy: 0.7334
Epoch 00045: saving model to checkpoints_optimized_v3\weights.45.hdf5
804/804 [==============================] - 1s 630us/step - loss: 0.5458 - accuracy: 0.7320
Epoch 46/100
804/804 [==============================] - 1s 627us/step - loss: 0.5456 - accuracy: 0.7312
Epoch 47/100
804/804 [==============================] - 1s 636us/step - loss: 0.5458 - accuracy: 0.7316
Epoch 48/100
804/804 [==============================] - 0s 617us/step - loss: 0.5453 - accuracy: 0.7317
Epoch 49/100
804/804 [==============================] - 1s 623us/step - loss: 0.5456 - accuracy: 0.7321
Epoch 50/100
566/804 [====================>.........] - ETA: 0s - loss: 0.5442 - accuracy: 0.7335
Epoch 00050: saving model to checkpoints_optimized_v3\weights.50.hdf5
804/804 [==============================] - 1s 636us/step - loss: 0.5455 - accuracy: 0.7325
Epoch 51/100
804/804 [==============================] - 1s 642us/step - loss: 0.5450 - accuracy: 0.7330
Epoch 52/100
804/804 [==============================] - 1s 634us/step - loss: 0.5451 - accuracy: 0.7328
Epoch 53/100
804/804 [==============================] - 1s 639us/step - loss: 0.5454 - accuracy: 0.7317
Epoch 54/100
804/804 [==============================] - 1s 637us/step - loss: 0.5450 - accuracy: 0.7317
Epoch 55/100
564/804 [====================>.........] - ETA: 0s - loss: 0.5426 - accuracy: 0.7338
Epoch 00055: saving model to checkpoints_optimized_v3\weights.55.hdf5
804/804 [==============================] - 1s 641us/step - loss: 0.5450 - accuracy: 0.7319
Epoch 56/100
804/804 [==============================] - 1s 627us/step - loss: 0.5452 - accuracy: 0.7319
Epoch 57/100
804/804 [==============================] - 0s 618us/step - loss: 0.5449 - accuracy: 0.7324
Epoch 58/100
804/804 [==============================] - 1s 649us/step - loss: 0.5452 - accuracy: 0.7322
Epoch 59/100
804/804 [==============================] - 0s 622us/step - loss: 0.5447 - accuracy: 0.7327
Epoch 60/100
489/804 [=================>............] - ETA: 0s - loss: 0.5455 - accuracy: 0.7317
Epoch 00060: saving model to checkpoints_optimized_v3\weights.60.hdf5
804/804 [==============================] - 1s 628us/step - loss: 0.5451 - accuracy: 0.7323
Epoch 61/100
804/804 [==============================] - 0s 612us/step - loss: 0.5444 - accuracy: 0.7318

Epoch 62/100
804/804 [==============================] - 0s 612us/step - loss: 0.5449 - accuracy: 0.7324
Epoch 63/100
804/804 [==============================] - 0s 611us/step - loss: 0.5446 - accuracy: 0.7318
Epoch 64/100
804/804 [==============================] - 0s 607us/step - loss: 0.5446 - accuracy: 0.7320
Epoch 65/100
494/804 [=================>............] - ETA: 0s - loss: 0.5391 - accuracy: 0.7379
Epoch 00065: saving model to checkpoints_optimized_v3\weights.65.hdf5
804/804 [==============================] - 1s 627us/step - loss: 0.5443 - accuracy: 0.7329
Epoch 66/100
804/804 [==============================] - 0s 610us/step - loss: 0.5443 - accuracy: 0.7330
Epoch 67/100
804/804 [==============================] - 0s 608us/step - loss: 0.5445 - accuracy: 0.7324
Epoch 68/100
804/804 [==============================] - 0s 613us/step - loss: 0.5446 - accuracy: 0.7324
Epoch 69/100
804/804 [==============================] - 0s 611us/step - loss: 0.5446 - accuracy: 0.7326
Epoch 70/100
489/804 [=================>............] - ETA: 0s - loss: 0.5420 - accuracy: 0.7359
Epoch 00070: saving model to checkpoints_optimized_v3\weights.70.hdf5
804/804 [==============================] - 1s 628us/step - loss: 0.5444 - accuracy: 0.7334
Epoch 71/100
804/804 [==============================] - 0s 613us/step - loss: 0.5446 - accuracy: 0.7325
Epoch 72/100
804/804 [==============================] - 0s 613us/step - loss: 0.5442 - accuracy: 0.7326
Epoch 73/100
804/804 [==============================] - 0s 610us/step - loss: 0.5444 - accuracy: 0.7328
Epoch 74/100
804/804 [==============================] - 0s 611us/step - loss: 0.5442 - accuracy: 0.7334
Epoch 75/100
484/804 [=================>............] - ETA: 0s - loss: 0.5441 - accuracy: 0.7330
Epoch 00075: saving model to checkpoints_optimized_v3\weights.75.hdf5
804/804 [==============================] - 1s 632us/step - loss: 0.5442 - accuracy: 0.7327
Epoch 76/100
804/804 [==============================] - 0s 613us/step - loss: 0.5441 - accuracy: 0.7318
Epoch 77/100
804/804 [==============================] - 1s 646us/step - loss: 0.5441 - accuracy: 0.7329
Epoch 78/100
804/804 [==============================] - 0s 617us/step - loss: 0.5441 - accuracy: 0.7331
Epoch 79/100
804/804 [==============================] - 0s 616us/step - loss: 0.5441 - accuracy: 0.7317
Epoch 80/100
406/804 [==============>...............] - ETA: 0s - loss: 0.5429 - accuracy: 0.7336
Epoch 00080: saving model to checkpoints_optimized_v3\weights.80.hdf5
804/804 [==============================] - 1s 629us/step - loss: 0.5441 - accuracy: 0.7326
Epoch 81/100
804/804 [==============================] - 0s 606us/step - loss: 0.5440 - accuracy: 0.7332
Epoch 82/100
804/804 [==============================] - 0s 612us/step - loss: 0.5439 - accuracy: 0.7329
Epoch 83/100
804/804 [==============================] - 0s 611us/step - loss: 0.5440 - accuracy: 0.7317
Epoch 84/100
804/804 [==============================] - 0s 615us/step - loss: 0.5437 - accuracy: 0.7331
Epoch 85/100
408/804 [==============>...............] - ETA: 0s - loss: 0.5451 - accuracy: 0.7334
Epoch 00085: saving model to checkpoints_optimized_v3\weights.85.hdf5
804/804 [==============================] - 1s 627us/step - loss: 0.5436 - accuracy: 0.7324
Epoch 86/100
804/804 [==============================] - 0s 617us/step - loss: 0.5441 - accuracy: 0.7322
Epoch 87/100
804/804 [==============================] - 0s 611us/step - loss: 0.5438 - accuracy: 0.7326
Epoch 88/100
804/804 [==============================] - 0s 613us/step - loss: 0.5436 - accuracy: 0.7339
Epoch 89/100
804/804 [==============================] - 0s 608us/step - loss: 0.5441 - accuracy: 0.7322
Epoch 90/100
409/804 [==============>...............] - ETA: 0s - loss: 0.5442 - accuracy: 0.7336
Epoch 00090: saving model to checkpoints_optimized_v3\weights.90.hdf5
804/804 [==============================] - 1s 629us/step - loss: 0.5436 - accuracy: 0.7322
Epoch 91/100
804/804 [==============================] - 1s 622us/step - loss: 0.5438 - accuracy: 0.7324
Epoch 92/100
804/804 [==============================] - 1s 627us/step - loss: 0.5436 - accuracy: 0.7325
Epoch 93/100
804/804 [==============================] - 0s 611us/step - loss: 0.5436 - accuracy: 0.7319
Epoch 94/100
804/804 [==============================] - 0s 615us/step - loss: 0.5434 - accuracy: 0.7322
Epoch 95/100
396/804 [=============>................] - ETA: 0s - loss: 0.5449 - accuracy: 0.7308
Epoch 00095: saving model to checkpoints_optimized_v3\weights.95.hdf5
804/804 [==============================] - 1s 639us/step - loss: 0.5435 - accuracy: 0.7328
Epoch 96/100
804/804 [==============================] - 0s 613us/step - loss: 0.5437 - accuracy: 0.7330
Epoch 97/100
804/804 [==============================] - 0s 616us/step - loss: 0.5434 - accuracy: 0.7337
Epoch 98/100
804/804 [==============================] - 0s 613us/step - loss: 0.5436 - accuracy: 0.7335
Epoch 99/100
804/804 [==============================] - 0s 615us/step - loss: 0.5433 - accuracy: 0.7322
Epoch 100/100
404/804 [==============>...............] - ETA: 0s - loss: 0.5507 - accuracy: 0.7291
Epoch 00100: saving model to checkpoints_optimized_v3\weights.100.hdf5
804/804 [==============================] - 1s 644us/step - loss: 0.5434 - accuracy: 0.7334

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5511 - accuracy: 0.7329
Loss: 0.551115870475769, Accuracy: 0.7329446077346802

In [20]:
# Export our model to HDF5 file
nn.save("trained_application_optimized_v3.h5")